# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = [
      "nvme"
      "xhci_pci"
      "usb_storage"
      "sd_mod"
      "sdhci_pci"
    ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
    # Don't mount /nix/store as read-only — it shares the same ext4 partition
    # as /persist, and an ro remount propagates to the entire device, making
    # all impermanence bind mounts (including ~/.claude) read-only.
    nixStoreMountOpts = [ ];
  };

  fileSystems = {
    "/" = {
      device = "none";
      fsType = "tmpfs";
      options = [
        "defaults"
        "size=6G"
        "mode=755"
      ];
    };

    "/persist" = {
      device = "/dev/disk/by-uuid/4e9ef302-7d6f-48f8-a881-d0bd5c47ff02";
      fsType = "ext4";
      neededForBoot = true;
      options = [ "defaults" ];
    };

    "/nix" = {
      device = "/persist/nix";
      fsType = "none";
      options = [ "bind" ];
    };

    "/mnt" = {
      device = "/dev/disk/by-uuid/6f021149-57b1-4ae8-99eb-99b1e8430336";
      fsType = "btrfs";
      options = [
        "compress=zstd"
        "noatime"
      ];
    };

    "/boot/efi" = {
      device = "/dev/disk/by-uuid/5090-32C8";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/d1ae50c9-4370-49e8-b70b-a904fbbc7722"; } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
