wallpaper {
    monitor = eDP-1
    path = /home/ben/pictures/wallpaper/Knights-of-Sidonia.png
    fit_mode = fill
}

wallpaper {
    monitor =
    path = /home/ben/pictures/wallpaper/Knights-of-Sidonia.png
    fit_mode = fill
}

splash = false
