# Per-device overrides
device {
  name = cherry-usb-keyboard
  kb_layout = us
  kb_variant = intl,
  kb_options = caps:swapescape, compose:menu
}

input {
  kb_layout = de
  kb_options = caps:swapescape
  numlock_by_default = true
  follow_mouse = 2
  repeat_delay = 200
  repeat_rate = 40

  touchpad {
    natural_scroll = true
    tap-to-click = true
    disable_while_typing = true
  }

  sensitivity = 0
}

gestures {
  workspace_swipe = on
  workspace_swipe_fingers = 4
  workspace_swipe_distance = 250
  workspace_swipe_invert = true
  workspace_swipe_min_speed_to_force = 15
  workspace_swipe_cancel_ratio = 0.5
  workspace_swipe_create_new = false
}
