# See https://wiki.hyprland.org/Configuring/Monitors/
monitor = DP-1, preferred, auto, 1.00
monitor = eDP-1, preferred, auto, 1.666667
monitor = HDMI-A-1, preferred, 0x0, 1.00
monitor = X11-1, 1024x768@60.00000, 0x0, 1.00
monitor = desc:BNQ BenQ GL2580 JCJ07368019, 1920x1080, auto-right, 1
monitor = desc:Samsung Electric Company S24D330 H4LHC17246, preferred, auto-left, 1
monitor = desc:Samsung Electric Company S24D330 0x5A5A5131, preferred, auto-left, 1
monitor = desc:Lenovo Group Limited LEN C32q-20 0x01010101, preferred, auto-left, 1
monitor = , preferred, auto, 1, mirror, eDP-1
monitor = , preferred, auto, 1
