# Persistent workspaces
workspace = 1, monitor:eDP-1, persistent:true
workspace = 2, monitor:DP-1, persistent:true
workspace = 3, monitor:DP-1, persistent:true

# Named workspaces
workspace = name:web, monitor:DP-1, default:true, persistent:true, on-created-empty:$browser
workspace = name:terminal, monitor:DP-1, persistent:true, on-created-empty:$terminal
workspace = name:email, monitor:eDP-1, persistent:true, on-created-empty:thunderbird
workspace = name:music, monitor:DP-1, persistent:true, on-created-empty:spotify
workspace = name:coding, on-created-empty:wezterm, monitor:DP-1
workspace = special, on-created-empty:$terminal
