#!/bin/bash

# If any command fails, exit immediately with that command's exit status
set -eo pipefail

# Find all changed files for this commit
# Compute the diff only once to save a small amount of time.
CHANGED_FILES=$(git diff --name-only --cached --diff-filter=ACMR)
# Get only changed files that match our file suffix pattern
get_pattern_files() {
    pattern=$(echo "$*" | sed "s/ /\$\\\|/g")
    echo "$CHANGED_FILES" | { grep "$pattern$" || true; }
}
# Get all changed python files
HTML_FILES=$(get_pattern_files .html)

if [[ -n "$HTML_FILES" ]]
then
    # Run script against changed html files for this commit
    for f in $HTML_FILES; do
        python utilities/add_js_script_to_html.py --source "$f" --dest "$f"
        echo "added js snippet to html script" "$f"
    done
fi
