# Per-device overrides
device {
  name = cherry-usb-keyboard
  kb_layout = us
  kb_options = caps:swapescape, compose:menu
}
device {
  name = rapoo-rapoo-5g-wireless-device
  kb_layout = us
  kb_options = caps:swapescape, compose:menu
}

input {
  kb_layout = de
  kb_options = caps:swapescape
  numlock_by_default = true
  follow_mouse = 2
  repeat_delay = 200
  repeat_rate = 40

  touchpad {
    natural_scroll = true
    tap-to-click = true
    disable_while_typing = true
  }

  sensitivity = 0
}

# Gestures (new 0.54 syntax: fingers, direction, action)
gesture = 4, horizontal, workspace

xwayland {
  force_zero_scaling = true
}
