name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  nix:
    name: Flake Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22

      - name: Prepare CI secrets input
        run: |
          mkdir -p .ci-secrets
          cp secrets/secrets.example.yaml .ci-secrets/secrets.yaml
          cp secrets/ssh-hosts.example.nix .ci-secrets/ssh-hosts.nix
          cp secrets/rbw.example.nix .ci-secrets/rbw.nix
          cp secrets/mail-accounts.example.nix .ci-secrets/mail-accounts.nix

      - name: Build checks output
        run: |
          nix run nixpkgs#nix-fast-build -- \
            --flake .#checks.x86_64-linux \
            --override-input nix-secrets path:./.ci-secrets \
            --no-link \
            --no-nom

      - name: Build EC2 image output
        run: nix build --print-build-logs --override-input nix-secrets path:./.ci-secrets .#ec2-amazon

      - name: Evaluate host toplevel derivations
        run: nix eval --raw --override-input nix-secrets path:./.ci-secrets .#nixosConfigurations.thinkpad.config.system.build.toplevel.drvPath
      - name: Evaluate server host toplevel derivation
        run: nix eval --raw --override-input nix-secrets path:./.ci-secrets .#nixosConfigurations.ec2.config.system.build.toplevel.drvPath
